rh_dbt:
  outputs:
    dev:
      database: MSSQL_DATABASE
      schema: dbo
      host: mssql
      password: your_password_for_mssql
      port: 1433
      threads: 4
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      user: sa
      encrypt: false
      trust_cert: true
  target: dev
